### ISSUE TITLE
Could you please create a simple Spring MVC Security user registration and forgot password example?

### ISSUE THREAD

**Issue by ghost** [OhadR/authentication-flows#64]

**Comment by OhadR** [comment]
I have a small client-app that uses "auth-flows". Is that what you mean?
You can find this app here: https://github.com/OhadR/Authentication-Flows

**Comment by ghost** [comment]
Hey thanks for your reply and nice example. I'm using your same project (with no customization yet), while deploying on tomcat web server I'm getting following error, not sure why it's causing the. Could you please guide?

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authFlowsProperties': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.lang.String com.ohadr.auth_flows.config.AuthFlowsProperties.accountActivatedEndpointUrl; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'com.ohadr.auth-flows.endpoints.accountActivatedEndpointUrl'

**Comment by OhadR** [comment]
Yes i can answer; could you please post this question in stackoverflow.com,
and i will answer there? This way it might help others in the future.
Btw there is a tag in stackoverflow for "authentication flows"  .

Thanks!
Ohad

**Comment by ghost** [comment]
OK, I've created issue on stackoverflow.com. (http://stackoverflow.com/questions/29479605/could-not-resolve-placeholder-com-ohadr-auth-flows-endpoints-accountactivateden). Could you please reply?

**Comment by ghost** [comment]
Could you please update?

**Comment by OhadR** [comment]
Hi
I have limited access to internet. I will answer your question this evening
as soon as i get access to web.

**Comment by OhadR** [comment]
answered (in SO)

**Comment by ghost** [comment]
Could you please tell me where did you respond?

**Comment by OhadR** [comment]
here,to the question u asked:
http://stackoverflow.com/questions/29479605/could-not-resolve-placeholder-com-ohadr-auth-flows-endpoints-accountactivateden/29496092#29496092

---

Ohad Redlich [image: linked-in with me]
http://il.linkedin.com/in/ohadredlich/[image: Join my Facebook Page]
https://www.facebook.com/ohadr.photography  https://github.com/OhadR
http://stackoverflow.com/users/421642/ohadr
