### ISSUE TITLE
Keystore generation fails

### ISSUE THREAD

**Issue by devabe** [OhadR/authentication-flows#76]
On common-crypto : 

- the DefaultCryptoProvider fails generation of JCEKS keystore generation

- KeystoreServiceImpl#afterPropertiesSet code is commented so getPrivateKey() and getPublicKey() return null

<com.ohadr.common-crypto.version>2.1-RELEASE</com.ohadr.common-crypto.version>
com.ohadr.crypto.createKeystoreFileIfNotExist=true

Please explain how to generate the keystore and how to fill keys on KeystoreServiceImpl.

Thank you.

**Comment by devabe** [comment]
Found solution.

1. It is necessary to put this code on common-crypt => KeystoreServiceImpl :
```

@Service("keystoreService")
public class KeystoreServiceImpl implements InitializingBean, KeystoreService
{
	@Autowired
	private CryptoProperties cryptoProperties;

	private PrivateKey privateKey;
	private PublicKey publicKey;

	public void afterPropertiesSet() throws Exception
	{
		try
		{
			KeyStore ks = KeyStore.getInstance("JCEKS");
			ks.load(new FileInputStream(cryptoProperties.getSimpleKeystore()), cryptoProperties.getSimplePassword().toCharArray());

			privateKey = (PrivateKey) ks.getKey(cryptoProperties.getKeyAlias(), cryptoProperties.getSimplePassword().toCharArray());

			publicKey = ks.getCertificate(cryptoProperties.getKeyAlias()).getPublicKey();
		}
		catch (Throwable e)
		{
			throw new IllegalArgumentException("Failed to read the private token key from the keystore", e);
		}
	}

	public PrivateKey getPrivateKey()
	{
		return privateKey;
	}

	public PublicKey getPublicKey()
	{
		return publicKey;
	}
}

```
2. generate JCEKS with java Keytool :

`keytool -genkeypair -alias ohadr -dname cn=localhost -validity 365 -keyalg DSA -keysize 1024 -keypass secret -storetype jceks -keystore keystore.jck -storepass secret`

**Comment by OhadR** [comment]
thanks!

did you see this, in the wiki, regarding  the keytool? https://github.com/OhadR/oAuth2-sample#keystore-things-to-know

**Comment by OhadR** [comment]
@devabe  if this problem is solved, can you please close this issue?

**Comment by devabe** [comment]
done.

thank you

2018-03-31 20:44 GMT+02:00 OhadR <notifications@github.com>:

**Comment by OhadR** [comment]
thanks for closing. 

if you have another issue, please do not hesitate to open a new one here (e.g. "`check-token-enabled`").
